# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivado/lab6_2/lab6_2.srcs/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0.xci
# IP: The module: 'mb_block_1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/lab6_2/labb6.gen/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado/lab6_2/labb6.gen/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Vivado/lab6_2/lab6_2.srcs/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0.xci
# IP: The module: 'mb_block_1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/lab6_2/labb6.gen/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado/lab6_2/labb6.gen/sources_1/bd/mb_block_1/ip/mb_block_1_mdm_1_0/mb_block_1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
